accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

mango_plane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spots/', include('spots.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spots/urls.py
from django.urls import path
from . import views
app_name = 'spots'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update_spot/', views.update_spot, name='update_spot'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:spot_pk>/', views.detail, name='detail'),
    path('<int:spot_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:spot_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:spot_pk>/likes/',views.likes, name='likes'),
    path('<int:spot_pk>/comments/<int:comment_pk>/likes/',views.comment_likes, name = 'comment_likes'),
    path('search/', views.search, name='search'),
    path('delete_recently_viewed_spots/', views.delete_recently_viewed_spots, name='delete_recently_viewed_spots'),
    path('city/', views.city, name='city'),
    ]

spots/models.py
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django.utils.safestring import mark_safe


class Spot(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_spots')
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    image   = models.ImageField(upload_to='tourlist_destinations/', null=True, blank=True)
    category   = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    price_range = models.CharField(max_length=20)
    parking = models.BooleanField(default=False)
    website = models.URLField(max_length=200, null=True, blank=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    
    def calculate_average_rating(self):
        comments = self.comment_set.all()
        if not comments:
            return 0

        total_rating = sum([float(comment.vote) for comment in comments])
        average_rating = total_rating / len(comments)
        return round(average_rating, 1)


class Comment(models.Model):
    VOTE_CHOICES = (
        (5.0, mark_safe('<i class="far fa-laugh-squint EmoticonPicker__Icon EmoticonPicker__Icon--Neutral"></i> 좋았다')),
        (3.0, mark_safe('<i class="far fa-meh EmoticonPicker__Icon EmoticonPicker__Icon--Neutral"></i>괜찮다')),
        (1.0, mark_safe('<i class="far fa-frown EmoticonPicker__Icon EmoticonPicker__Icon--Neutral"></i>나쁘다')),
    )
    vote = models.FloatField(choices=VOTE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    article = models.ForeignKey(Spot, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)

class CommentImage(models.Model):
    image = models.ImageField(upload_to='tourlist_destinations/')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='images')
    

spots/forms.py
from django import forms
from .models import Spot, Comment, CommentImage
from django.forms import formset_factory
from django.contrib.auth import get_user_model

class SpotForm(forms.ModelForm):
    title = forms.CharField(
        label='여행지',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width: 250px',
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 5,
                'style': 'width: 250px',
            }
        ),
    )
    category = forms.CharField(
        label='카테고리',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width: 250px',
            }
        ),
    )
    address = forms.CharField(
        label='주소',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style' : 'width: 250px',
                'id' : 'address_kakao',
            }
        ),
    )
    price_range = forms.CharField(
        label='가격대',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style' : 'width: 250px',
                'name' : 'charge',
            }
        ),
    )
    parking = forms.BooleanField(
        label='주차 가능 여부',
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
            }
        ),
    )
    website = forms.URLField(
        label='웹사이트',
        required=False,
        widget=forms.URLInput(
            attrs={
                'class': 'form-control',
                'style' : 'width: 250px',
            }
        ),
    )

    class Meta:
        model = Spot
        fields = ('title', 'content', 'image', 'category', 'address', 'price_range', 'parking', 'website',)
        labels = {
            'image': '이미지',

        }


class CommentForm(forms.ModelForm):
    vote = forms.ChoiceField(choices=Comment.VOTE_CHOICES)
    content = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'ReviewEditor__Editor',
            'maxlength': '10000',
            'style': 'overflow: hidden; overflow-wrap: break-word; width: 644px; height: 150px; border: 1px solid #DBDBDB;',
        }),
    )
    vote = forms.ChoiceField(
        label='',
        choices=Comment.VOTE_CHOICES,
        widget=forms.RadioSelect(attrs={
            'class': 'emojiFlex',
            'style': 'display: none;',
            'onclick': "var radio = document.getElementsByName('vote');\
                        for (var i=0; i<radio.length; i++) {\
                            if (radio[i].checked) {\
                                radio[i].parentNode.style.color='#ff9008';\
                                radio[i].parentNode.querySelector('.EmoticonPicker__Icon').style.color = '#ff9008';\
                            } else {\
                                radio[i].parentNode.style.color='#959595';\
                                radio[i].parentNode.querySelector('.EmoticonPicker__Icon').style.color = '#959595';\
                            }\
                        }"
        }),
    )

    class Meta:
        model = Comment
        fields = ('vote', 'content')  # 'image'를 제거합니다.

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        spot = kwargs.pop('spot')  # spot 인자를 받아옵니다.
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if self.request:
            self.fields['content'].widget.attrs['placeholder'] = f"{self.request.user}님, 이번 여행은 어떠셨나요? 여행지의 분위기와 후기가 궁금해요!"
    
    def clean_vote(self):
        vote = self.cleaned_data.get('vote')
        return float(vote)
        
class CommentImageForm(forms.ModelForm):
    class Meta:
        model = CommentImage
        fields = ('image',)

CommentImageFormSet = forms.formset_factory(CommentImageForm, extra=1, max_num=30)

spots/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Spot, Comment
from .forms import SpotForm, CommentForm, CommentImageFormSet, CommentImage
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.http import JsonResponse
from utils.map import get_latlng_from_address
import os

def index(request):
    spots = Spot.objects.order_by('-pk')
    spots_with_ratings = []
    for spot in spots:
        average_rating = spot.calculate_average_rating()
        spots_with_ratings.append((spot, average_rating))
    context = {
        'spots': spots,
        'spots_with_ratings': spots_with_ratings,
    }
    return render(request, 'spots/index.html', context)

def detail(request, spot_pk):
    spot = Spot.objects.get(pk=spot_pk)
    comments = spot.comment_set.all()
    comment_count = comments.count()
    kakao_script_key = os.getenv('kakao_script_key')
    like_count = spot.comment_set.filter(vote=5.0).count()
    soso_count = spot.comment_set.filter(vote=3.0).count()
    dislike_count = spot.comment_set.filter(vote=1.0).count()
    address = spot.address
    latitude, longitude = get_latlng_from_address(address)
    average_rating = spot.calculate_average_rating()

    image_exists = any(comment.images.exists() for comment in comments)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST, request.FILES, spot=spot)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.spot = spot
            comment.save()
            return redirect('spots:detail', spot_pk=spot.pk)
    else:
        comment_form = CommentForm(spot=spot)
    
    context = {
        'spot': spot,
        'comments': comments,
        'comment_form': comment_form,
        'comment_count': comment_count,
        'like_count': like_count,
        'dislike_count': dislike_count,
        'soso_count': soso_count,
        'average_rating': average_rating,
        'image_exists': image_exists,
        'kakao_script_key': kakao_script_key,
        'latitude': latitude,
        'longitude': longitude,
    }
    
    return render(request, 'spots/detail.html', context)





@login_required
def create(request):
    if request.method == "POST":
        form = SpotForm(request.POST, request.FILES)
        if form.is_valid():
            spot = form.save(commit=False)
            spot.user = request.user
            spot.save()
            return redirect('spots:detail', spot_pk=spot.pk)

    else:
        form = SpotForm()

    context = {
        'form': form,
    }

    return render(request, 'spots/create.html', context)

@login_required
def update_spot(request, pk):
    spot = Spot.objects.get(pk=pk)

    if request.user == spot.user:
        if request.method == 'POST':
            form = SpotForm(request.POST, request.FILES, instance=spot)
            if form.is_valid():
                form.save()
                return redirect('spots:detail', spot.pk)
        else:
            form = SpotForm(instance=spot)
    else:
        return redirect('spots:index')
    context = {
        'form': form,
        'spot': spot,
    }
    return render(request, 'spots/update_spot.html', context)
# requsert -> spot으로 나중에 

@login_required
def delete(request, pk):
    spot = Spot.objects.get(pk=pk)
    if request.user == request.user:
        spot = spot.objects.get(pk=pk)
        spot.delete()

    return redirect('spots:index')

@login_required
def comment_create(request, spot_pk):
    spot = Spot.objects.get(pk=spot_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, spot=spot, request=request)
        formset = CommentImageFormSet(request.POST, request.FILES, prefix='commentimage_set')

        if form.is_valid() and formset.is_valid():
            comment = form.save(commit=False)
            comment.article = spot
            comment.user = request.user
            comment.save()

            for image_form in formset:
                if 'commentimage_set-0-image' in request.FILES:
                    for img in request.FILES.getlist('commentimage_set-0-image'):
                        image = CommentImage(comment=comment, image=img)
                        image.save()
                    break

            return redirect('spots:detail', spot_pk=spot.pk)
    else:
        form = CommentForm(spot=spot, request=request)
        formset = CommentImageFormSet(prefix='commentimage_set')

    context = {
        'form': form,
        'formset': formset,
        'spot': spot,
    }
    return render(request, 'spots/comment_create.html', context)

@login_required
def comment_delete(request, spot_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()

    return redirect('spots:detail', spot_pk)


@login_required
def likes(request, spot_pk):
    spot = Spot.objects.get(pk=spot_pk)
    if request.user in spot.like_users.all():
        spot.like_users.remove(request.user)
        liked = False
    else:
        spot.like_users.add(request.user)
        liked = True
    data = {
        'liked': liked,
    }
    return JsonResponse(data)

@login_required
def comment_likes(request, spot_pk, comment_pk):
    comment =  Comment.objects.get(pk=comment_pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('spots:detail', spot_pk)

def search(request):
    keyword = request.GET.get('keyword')
    spots = Spot.objects.filter(title__contains = keyword) # SELECT ... FROM ... LIKE '%<keyword>%'
    spots_with_ratings = []
    len_element = 8
    paginator = Paginator(spots, len_element)
    page_number = request.GET.get('page')
    if page_number == None :
        page_number = 1
    page_obj = paginator.get_page(page_number)
    for spot in page_obj:
        average_rating = spot.calculate_average_rating()
        spots_with_ratings.append((spot, average_rating))
    len_page = (len(spots) + 1) // len_element
    pages = range(1, len_page + 1)
    context = {
        'spots': page_obj,
        'keyword': keyword,
        'pages': pages,
        'page_number': int(page_number),
        'spots_with_ratings': spots_with_ratings,
    }
    return render(request, 'spots/search.html', context)

@require_POST
def delete_recently_viewed_spots(request):
    request.session['viewed_spots_pks'] = []
    return JsonResponse({}, status=200)

def city(request):
    tag = request.GET.get('city')
    spots = Spot.objects.filter(address__contains=tag)
    spots_with_ratings = []
    for spot in spots:
        average_rating = spot.calculate_average_rating()
        spots_with_ratings.append((spot, average_rating))
    comments = Comment.objects.filter(article__in=spots)
    context = {
        'spots': spots,
        'spots_with_ratings': spots_with_ratings,
        'comments': comments
    }
    return render(request, 'spots/city.html', context)



    # spots = Spot.objects.order_by('-pk')
    # spots_with_ratings = []
    # for spot in spots:
    #     average_rating = spot.calculate_average_rating()
    #     spots_with_ratings.append((spot, average_rating))
    # context = {
    #     'spots': spots,
    #     'spots_with_ratings': spots_with_ratings,
    # }

spots/templates/spots/detail.html
{% extends "base.html" %}
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

{% block style %}

.wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap * {padding: 0;margin: 0;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;}
    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}
    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}
    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}
    .info .link {color: #5085BB;}
.EmoticonPicker__Icon {
  font-size: 44px;
  margin: 8px;
  color: #ff9008;
}
.Icon {
  font-size: 32px;
  
}
.Icon2 {
  font-size: 32px;
  color: #959595;
}
.Icon:hover .fas {
  color: #ff9008;
}
.size {
  object-fit: cover;
  width: 430px;
  height: 300px;
}
.review-write-link:hover .review-write-text,
.review-write-link:hover .review-write-icon {
  color: #ff9008;
}
.review-write-link {
  color: #959595;
  text-decoration: none;
}
.review-write-text {
  color: #959595;
}
.like-spot-icon {
  color: #959595;
}

.like-spot:hover .like-spot-icon,
.like-spot-icon.active {
  color: #ff9008;
}

.like-spot-text {
  color: #959595;
}

.like-spot:hover .like-spot-text,
.like-spot-text.active {
  color: #ff9008;
}
none-margin-bottom{
  margin-bottom: 0px;
}

.image-container {
  display: flex;
  overflow-x: scroll;
  gap: 16px;
  width: 100%;
  height: 400px; /* 이미지가 가로 방향으로 스크롤되는 부모 요소의 높이를 지정합니다 */
}

.scroll-button {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  z-index: 1;
  font-size: 3em;
}

.scroll-left {
  left: 0;
}

.scroll-right {
  right: 0;
}

.background-image {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  z-index: -1;
}

.text {
  position: relative;
  z-index: 1;
  text-align: center;
  margin-top: 200px;
}

.removeButton{
  color: black;
}

.removeButton:hover {
  color: black;
}
.fixed-width-img {
  width: 400px;
  height: 400px;
  object-fit: cover;
}

{% endblock style %}

{% block content %}
<!-- 이모티콘 link -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<div style="position: relative;">
  <div class="image-container" id="imageContainer">
    {% if image_exists %}
      {% for comment in comments %}
        {% for image in comment.images.all %}
        <div>
          <div class="">
            <img src="{{ image.image.url }}" class="fixed-width-img" alt="Comment image">
          </div>
        </div>
        {% endfor %}
      {% endfor %}
      <i class="fas fa-chevron-left scroll-button scroll-left" onclick="scrollImageContainer(-1)"></i>
      <i class="fas fa-chevron-right scroll-button scroll-right" onclick="scrollImageContainer(1)"></i>
    {% else %}
      <div class="container">
        <img src="{% static 'headerimg.jpg' %}" alt="Header image" class="background-image">
        <h3 class="text" style="color: white;">이미지가 없습니다. 리뷰를 작성하고 사진을 올려주세요!</h3>
      </div>
    {% endif %}
  </div>
</div>

<script>
  const scrollAmount = 410;

  function scrollImageContainer(direction) {
    const imageContainer = document.getElementById('imageContainer');
    imageContainer.scrollLeft += scrollAmount * direction;
  }
</script>

<section class='container' style='max-width: 800px;'>
  <div class='d-flex justify-content-between mt-5'>
    <h3>{{spot.title}} <span style="color: #FF792A;">{{ average_rating }}</span></h3>
    <div class='d-grid gap-2 d-md-flex justify-content-md-end align-items-center'>
      {% if spot.user == user %}
        <a href="{% url 'spots:update_spot' spot.pk %}" class="btn btn-primary me-2 custom-button">
          <span>수정</span>
        </a>
        <form action="{% url 'spots:delete' spot.pk %}" method="POST" class="d-inline-block">
          {% csrf_token %}
          <input type="submit" value="삭제" class="btn btn-danger custom-button">
        </form>
      {% else %}
      {% endif %}
    
        <div class="d-flex flex-column align-items-center text-center review-write">
          <a href="{% url 'spots:comment_create' spot_pk=spot.pk %}" role="button" class="review-write-link" onclick="event.preventDefault(); writeReview(this);">
            <i class="fas fa-pencil-alt Icon review-write-icon custom-button mt-2 mn-n2"></i>
            <p class="mb-0 review-write-text">리뷰쓰기</p>
          </a>
        </div>
        
        <form class="like-form" method="POST" action="{% url 'spots:likes' spot.pk %}">
        <form action="{% url 'spots:likes' spot.pk %}" method="POST">
          {% csrf_token %}
          <div class="d-flex flex-column align-items-center like-spot">
            <button type="submit" class="btn btn-link p-0 Icon custom-button">
              <i class="fas fa-star like-spot-icon {% if request.user in spot.like_users.all %}active{% endif %}"></i>
            </button>
            <p class="mt-2 mb-0 like-spot-text {% if request.user in spot.like_users.all %}active{% endif %}">가고싶다</p>
          </div>
        </form>
        
      </div>
    </div>
    
    <hr>
    <p style="color: #959595;">{{ spot.content }}</p>
    <p style="color: #959595;">주소: {{ spot.address }}</p>
    <p style="color: #959595;">카테고리: {{ spot.category }}</p>
    <p style="color: #959595;">가격대: {{ spot.price_range }}</p>
    <p style="color: #959595;">주차: {% if spot.parking %} 가능 {% else %} 불가능 {% endif %}</p>
    {% if spot.website %}
    <p style="color: #959595;">웹사이트: <a href="{{ spot.website }}" style="color: black;">여행지 홈페이지로 가기</a></p>
    {% endif %}
    <div id="map" style="width:100%;height:350px;"></div>
    <hr>

    <p style="display: flex; justify-content: space-between; align-items: center;">리뷰 ({{ comment_count }}) 
      <span style="margin-left: auto;">
        전체 ({{ comment_count }}) |
        좋아요: ({{ like_count }}) |
        싫어요: ({{ dislike_count }}) |
        보통: ({{ soso_count }})
      </span>
    </p>


    {% for comment in comments %}
    <div class="row mt-4">
      <div class="col-2" style="display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center;">
        <a href="{% url 'accounts:profile' comment.user %}">
          <button type="button" style="width: 70px; height: 70px; padding: 0; box-sizing: border-box;" class="btn btn-lg rounded-circle me-2">
            <img class="rounded-circle" style="width: 100%; height: 100%; object-fit: cover; display: block; margin: auto;" src="{% if comment.user.image %}{{ comment.user.image.url }}{% else %}{% static 'not-found-user.png' %}{% endif %}" alt="Profile Image">
          </button>
          <p>{{ comment.user }}</p>
        </a>
      </div>

    <div class="col-8">
      <p style="color: #959595;">{{ comment.created_at|date:"Y-m-d" }}</p>
      <p>{{comment.content}}</p>
    </div>
    <div class="col-2">
      <div class="comment">
        {% if comment.vote == "5.0" %}
        <div class="d-flex flex-column align-items-center">
          <i class="far fa-laugh-squint EmoticonPicker__Icon EmoticonPicker__Icon--Positive"></i>
          <p class="mb-0" style="color: #ff9008;">좋았다</p>
        </div>
        {% elif comment.vote == "3.0" %}
        <div class="d-flex flex-column align-items-center">
          <i class="far fa-meh EmoticonPicker__Icon EmoticonPicker__Icon--Neutral"></i>
          <p class="mb-0" style="color: #ff9008;">괜찮다</p>
        </div>
        {% elif comment.vote == "1.0" %}
        <div class="d-flex flex-column align-items-center">
          <i class="far fa-frown EmoticonPicker__Icon EmoticonPicker__Icon--Negative"></i>
          <p class="mb-0" style="color: #ff9008;">나쁘다</p>
        </div>
        {% endif %}
      </div>
      {% if comment.user == user %}
      <div class="d-flex justify-content-end">
        <form action="{% url 'spots:comment_delete' spot.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="removeButton btn btn-link p-0">
            <i class="fas fa-eraser"></i>
          </button>
        </form>
      </div>
    {% endif %}
    </div>
</div>
  <hr>
  <form action=""></form>

  {% endfor %}
    </section>
    
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={{ kakao_script_key }}&libraries=services"></script>
    <script>
      const latitude = {{ latitude }};
      const longitude = {{ longitude }};
      const container = document.getElementById('map');
      const options = {
          center: new kakao.maps.LatLng(latitude, longitude),
          level: 3
      };
      const map = new kakao.maps.Map(container, options);
      const markerPosition = new kakao.maps.LatLng(latitude, longitude);
      const marker = new kakao.maps.Marker({
          position: markerPosition
      });
      {% comment %} marker.setMap(map); {% endcomment %}
      map.setCenter(markerPosition);

        var content = '<div class="wrap">' + 
          '    <div class="info">' + 
          '        <div class="title">' + 
          '            {{ spot.title }}' + 
          '        </div>' + 
          '        <div class="body">' + 
          '            <div class="img">' +

          '                <img src="{{ spot.image.url }}" width="73" height="70">' +
          '           </div>' + 
          '            <div class="desc">' + 
          '                <div class="ellipsis">{{ spot.address }}</div>' + 
          '                <div><a href={{ spot.website }} target="_blank" class="link">홈페이지</a></div>' + 
          '            </div>' + 
          '        </div>' + 
          '    </div>' +    
          '</div>';

        // 마커 위에 커스텀오버레이를 표시합니다
        // 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
        var overlay = new kakao.maps.CustomOverlay({
          content: content,
          map: map,
          position: marker.getPosition()       
        });

    function writeReview(link) {
      link.querySelector('.review-write-text').style.color = 'orange';
      link.querySelector('.review-write-icon').style.color = 'orange';
      window.location.href = link.href;
    }

    $(document).ready(function() {
      // When the like-form is submitted
      $('.like-form').submit(function(event) {
        // Prevent the form from submitting through HTTP
        event.preventDefault();
    
        // Get the form action and method
        var url = $(this).attr('action');
        var method = $(this).attr('method');
    
        // Send an AJAX request
        $.ajax({
          url: url,
          method: method,
          data: $(this).serialize(),  // Serialize the form data
          success: function(response) {
            // Update the like button icon and text
            var icon = $('.like-spot-icon', $(event.target));
            var text = $('.like-spot-text', $(event.target));
            if (icon.hasClass('active')) {
              icon.removeClass('active');
              text.removeClass('active');
            } else {
              icon.addClass('active');
              text.addClass('active');
            }
          },
          error: function(xhr, status, error) {
            // Handle the error
            console.error(xhr.responseText);
          }
        });
      });
    });
  </script>
{% endblock content %}
      