accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

mango_plane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spots/', include('spots.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spots/urls.py
from django.urls import path
from . import views
app_name = 'spots'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update_spot/', views.update_spot, name='update_spot'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:spot_pk>/', views.detail, name='detail'),
    path('<int:spot_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:spot_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:spot_pk>/likes/',views.likes, name='likes'),
    path('<int:spot_pk>/comments/<int:comment_pk>/likes/',views.comment_likes, name = 'comment_likes'),
    path('search/', views.search, name='search'),
    path('delete_recently_viewed_spots/', views.delete_recently_viewed_spots, name='delete_recently_viewed_spots'),
    path('city/', views.city, name='city'),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users', blank=True, null=True)
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'image',
            'password1',
            'password2',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.http import JsonResponse

def login(request):
    if request.user.is_authenticated:
        return redirect('spots:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('spots:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('spots:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('spots:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('spots:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('reviews:index')

@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
            'followings': [{'username': f.username, 'pk': f.pk} for f in you.followings.all()],
            'followers': [{'username': f.username,'pk': f.pk} for f in you.followers.all()]
        }
        
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)

def follower(request, user_pk):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)
    followers = [{'username': f.username, 'pk': f.pk} for f in user.followers.all()]
    return JsonResponse({'followers': followers})

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block style %}

* {
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}

.container {
  margin-top: 5%;
  text-align: center;
}

.login {
  margin-top: 50px;
}

.loginButton {
  width: 400px;
  background-color: lightgray;
  border: 1px solid lightgray;
  border-radius: 15px;
  margin-top: 30px;
  padding: 10px;
}

label {
  display: inline-block;
  width: 100px;
  font-weight: bold;
  margin-bottom: 10px;
}

input[type="text"], input[type="password"], input[type="email"] {
  width: 250px;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  margin-bottom: 10px;
}

input[type="submit"]:hover {
  background-color: orange;
}

{% endblock style %}

{% block content %}
  <div class="container">
    <h1>망고 플레인</h1>
    <p>로그인하면 가고 싶은 식당을 저장할 수 있어요!</p>
    <form class="login" action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <label for="{{ form.username.id_for_label }}">아이디</label>
      {{ form.username }}
      <br>
      <label for="{{ form.password.id_for_label }}">비밀번호</label>
      {{ form.password }}
      <br>
      <input class="loginButton" type="submit" value="로그인">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  mal {
    margin-left: 50px;
  }
  a {
    text-decoration: none; /* 밑줄 제거 */
  }
  .profile {
    width: 50px;
    height: 50px;
  }
  .profile--modal--box {
    border: 2px solid #682c0ec2;
  }
  .profile--followbtn{
    
  }
  .modal--profile--card {
    width: 20%;
  }
  
  .modal--profile--link {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  .profile--followbtn {
    width: 150px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
  }

  .followbtnBox {
    display: flex;
    justify-content: space-evenly;
  }
{% endblock style %}
{% block content %}
<div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="followersModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content profile--modal--box">
      <div class="modal-header">
        <h1 class="modal-title fs-5"  id="followersModalLabel">팔로워</h1>
      </div>
      <div class="modal-body" id = "f_follower_list">
      {% if request.user == person %}
        {% for follower in person.followers.all %}
          <div class="modal--profile--card">
            <a class="text-decoration-none link-secondary fw-bold modal--profile--link" href="{% url 'accounts:profile' follower.username %}">
              {% if follower.profile_image %}
                <div class="profile--image rounded-circle">
                  <img src="{{ follower.image.url }}" alt="" class="object-fit-fill profile">
                </div>
              {% else %}
                <div class="profile--image rounded-circle">
                  <img src="{% static 'not-found-user.png' %}" alt="profile_image_none" class="object-fit-fill profile">
                </div>
              {% endif %}
              <span>{{ follower }}</span></a>
          </div>
          {% endfor %}

      {% else %}
          <div id="followers-list"></div>
      {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="profile--followbtn" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- 팔로잉 Modal -->
<div class="modal fade" id="followingsModal" tabindex="-1" aria-labelledby="followingsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content profile--modal--box">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="followingsModalLabel">팔로잉</h1>
      </div>
      <div class="modal-body">
        {% for following in person.followings.all %}
        <div class="modal--profile--card">
          <a class="text-decoration-none link-secondary fw-bold modal--profile--link" href="{% url 'accounts:profile' following.username %}">
            {% if following.profile_image %}
              <div class="profile--image rounded-circle">
                <img src="{{ following.image.url }}" alt="" class="object-fit-fill profile">
              </div>
            {% else %}
              <div class="profile--image rounded-circle">
                <img src="{% static 'not-found-user.png' %}" alt="profile_image_none" class="object-fit-fill profile">
              </div>
            {% endif %}
            <span>{{ following }}</span></a>
        </div>
        {% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="profile--followbtn" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class = "container text-center">
    <div style = "display: inline-block;">
    <div class="card" class = "mx-auto" style = "width : 400px;">
      {% if person.image %}
        <img src="{{ person.image.url }}" class="card-img-top rounded-2 mx-auto mt-4" style = "width: 300px;" alt="image">
      {% else %}
        <img src="{% static 'not-found-user.png' %}" class="card-img-top rounded-2 mx-auto mt-4" alt="image">
      {% endif %}
      <div class="card-body mal">
        <h4 class="card-text card_title">{{ person.username }}</h4>
        <p class="card-text">{{spot.title}}</p>
        <p class="card-text">이름: {{ person.last_name }}{{ person.first_name }}</p> 
        <p class="card-text">이메일: {{ person.email }}</p> 
      </div>
      {% if request.user != person %}
      <div>
        <form id="follow-form" data-user-id="{{ person.pk }}">
          {% csrf_token %}
          {% if request.user in person.followers.all %}
            <input class="profile--followbtn" type="submit" value="Unfollow">
          {% else %}
            {% if request.user.is_authenticated %}
              <input class="profile--followbtn" type="submit" value="follow">
            {% else %}
              <input class="profile--followbtn" type="submit" value="follow" disabled>
            {% endif %}
          {% endif %}
        </form>
      </div>
      {% endif %}
      <div class="followbtnBox">
        <button type="button" class="profile--followbtn" data-bs-toggle="modal" data-bs-target="#followersModal">
          <span id="followers-count">{{ person.followers.all|length }}</span> 팔로워
        </button>

        <!-- 팔로잉 모달 버튼 -->
        <button type="button" class="profile--followbtn" data-bs-toggle="modal" data-bs-target="#followingsModal">
          <span id = 'followings-count'>{{ person.followings.all|length }}</span> 팔로잉 
        </button>
      </div>
    </div>
    {% comment %} <div class = 'd-flex'>
      <a href="{% url 'accounts:update' %}">
        <button type="button" class="btn btn-danger m-3">프로필 수정</button>
      </a>
      <a href="{% url 'accounts:password_change' %}">
        <button type="button" class="btn btn-danger m-3">비밀번호 변경</button>
      </a>
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger m-3" value="회원탈퇴">
      </form>
    </div> {% endcomment %}
  </div>
  <br>
</div>
{% endblock content %}

{% block script %}
<script>
  const followersModalBtn = document.querySelector('#followersModal');
  
  // Add event listeners to the modal buttons
  followersModalBtn.addEventListener('shown.bs.modal', function (event) {
    const userId = document.querySelector('#follow-form').dataset.userId;
    axios.get(`/accounts/${userId}/follower/`)
      .then((response) => {
        const followers = response.data.followers;
        const followersList = document.querySelector('#followers-list');
        followersList.innerHTML = '';
        followers.forEach(follower => {
          const followerTag = document.createElement('div');
          followerTag.className = "modal--profile--card";
          const followerLink = document.createElement('a');
          followerLink.className = "text-decoration-none link-secondary fw-bold modal--profile--link";
          followerLink.href = `/accounts/profile/${follower.username}`
          const followerImageDiv = document.createElement('div');
          followerImageDiv.className = "profile--image rounded-circle";
          if (follower.image) {
            const followerImage = document.createElement('img');
            followerImage.className = "object-fit-fill profile";
            followerImage.src = follower.image.url;
            followerImage.alt = `${follower.username}'s profile image`;
            followerImageDiv.appendChild(followerImage);
          } else {
            const followerImage = document.createElement('img');
            followerImage.className = "object-fit-fill profile";
            followerImage.src = "{% static 'not-found-user.png' %}";
            followerImage.alt = "profile_image_none";
            followerImageDiv.appendChild(followerImage);
          }
          followerLink.appendChild(followerImageDiv);
          const followerName = document.createElement('span');
          followerName.textContent = follower.username;
          followerLink.appendChild(followerName);
          followerTag.appendChild(followerLink);
          followersList.appendChild(followerTag);
        });
      });
  })
  

  const form = document.querySelector('#follow-form');
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  const followersList = document.querySelector('#followers-list');

  form.addEventListener('submit', function(event) {
    event.preventDefault();
    const userId = event.target.dataset.userId;

    axios({
      method: 'post',
      url:`/accounts/${userId}/follow/`,
      headers: {'X-CSRFToken': csrftoken},
    })
      .then((response) => {
        const isFollowed = response.data.is_followed;
        const followBtn = document.querySelector('#follow-form > input[type=submit]');
        if (isFollowed === true) {
          followBtn.value = 'Unfollow';
        } else {
          followBtn.value = 'follow';
        }
        const followingsCounterTag = document.querySelector('#followings-count');
        const followersCounterTag = document.querySelector('#followers-count');
        const followingsCountData = response.data.followings_count;
        const followersCountData = response.data.followers_count;
        followingsCounterTag.textContent = followingsCountData;
        followersCounterTag.textContent = followersCountData;

        // 팔로워 목록 출력
        followers.forEach(follower => {
          const followerTag = document.createElement('div');
          followerTag.className = "modal--profile--card";
          const followerLink = document.createElement('a');
          followerLink.className = "text-decoration-none link-secondary fw-bold modal--profile--link";
          followerLink.href = "#";
          const followerImageDiv = document.createElement('div');
          followerImageDiv.className = "profile--image rounded-circle";
          if (follower.profile_image) {
            const followerImage = document.createElement('img');
            followerImage.className = "object-fit-fill profile";
            followerImage.src = follower.image.url;
            followerImage.alt = `${follower.username}'s profile image`;
            followerImageDiv.appendChild(followerImage);
          } else {
            const followerImage = document.createElement('img');
            followerImage.className = "object-fit-fill profile";
            followerImage.src = "{% static 'not-found-user.png' %}";
            followerImage.alt = "profile_image_none";
            followerImageDiv.appendChild(followerImage);
          }
          followerLink.appendChild(followerImageDiv);
          const followerName = document.createElement('span');
          followerName.textContent = follower.username;
          followerLink.appendChild(followerName);
          followerTag.appendChild(followerLink);
          followersList.appendChild(followerTag);
        });
      })
  })
</script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block style %}
  .container {
    width: 1020px;
    text-align: center;
  }

  h1 {
    margin: 60px 0;
  }

  #signupform {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }

  input[type="text"], input[type="password"], input[type="email"] {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
  }

  #signup-submit {
    background-color: lightgray;
    color: #fff;
    border: none;
    margin-top: 20px;
    padding: 10px 20px;
    border-radius: 3px;
    cursor: pointer;
  }

  input[type="submit"]:hover {
    background-color: orange;
  }

  .form-group {
    display: flex;
    align-items: center;
  }
  
  .form-group label {
    flex-basis: 30%;
    margin-right: 10px;
  }
  
  .form-group input[type="text"],
  .form-group input[type="password"],
  .form-group input[type="email"] {
    flex: 1;
  }
{% endblock style %}
{% block content %}
  <div class="container">
    <h1>회원가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data" id = "signupform">
      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">이름</label>
        {{ form.first_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">성</label>
        {{ form.last_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">아이디</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label for="{{ form.password1.id_for_label }}">비밀번호</label>
        {{ form.password1 }}
      </div>
      <div class="form-group">
        <label for="{{ form.password2.id_for_label }}">비밀번호 확인</label>
        {{ form.password2 }}
      </div>
      <div class="form-group">
        <label for="{{ form.email.id_for_label }}">이메일</label>
        {{ form.email }}
      </div>
      <div class="form-group">
        {{ form.image }}
      </div>
      {% csrf_token %}
      <input type="submit" value="회원 가입" id = "signup-submit">
    </form>
  </div>
{% endblock content %}